# Generated by Django 4.2.16 on 2024-12-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id_capteur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_capteur', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureThreshold',
            fields=[
                ('id_threshold', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('min_value', models.FloatField(default=0.0)),
                ('max_value', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('mot_de_passe', models.TextField()),
                ('role', models.TextField()),
                ('token', models.TextField(blank=True, null=True)),
                ('id_telegram', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id_assignment', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_alerts', models.IntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHT.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature_detectee', models.FloatField()),
                ('debut_incident', models.DateTimeField()),
                ('fin_incident', models.DateTimeField(blank=True, null=True)),
                ('statut_incident', models.TextField()),
                ('id_capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHT.capteur')),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id_enregistrement', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('id_capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHT.capteur')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id_alerte', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('niveau_alerte', models.IntegerField()),
                ('id_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHT.incident')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHT.utilisateur')),
            ],
        ),
    ]
