# Generated by Django 4.2.16 on 2024-12-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_alter_enregistrement_date_enregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='token',
        ),
    ]
