# Generated by Django 4.2.16 on 2024-12-28 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_remove_utilisateur_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DHT.utilisateur'),
        ),
    ]
