# Generated by Django 4.2.16 on 2024-12-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_incident_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='type_incident',
            field=models.TextField(blank=True, null=True),
        ),
    ]
